[package]
name = "emplace"
version = "0.3.5-alpha.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
description = "Command-line tool to mirror installed software on multiple machines."
edition = "2018"
repository = "https://github.com/tversteeg/emplace"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["shell", "cli", "mirror", "sync"]
categories = ["command-line-utilities"]

[badges]
is-it-maintained-issue-resolution = { repository = "tversteeg/emplace" }
is-it-maintained-open-issues = { repository = "tversteeg/emplace" }

[dependencies]
anyhow = "1.0.31"
clap = "2.33.1"
colored = "1.9.3"
console = "0.11.3"
dialoguer = "0.6.2"
dirs = "2.0.2"
enum_dispatch = "0.3.1"
itertools = "0.9.0"
log = "0.4.8"
ron = "0.6.0"
run_script = "0.6.3"
serde = { version = "1.0.111", features = ["derive"] }
shellexpand = "2.0.0"
simplelog = "0.8.0"
strum = "0.18.0"
strum_macros = "0.18.0"
toml = "0.5.6"
is_executable = "0.1.2"

[package.metadata.deb]
maintainer = "Thomas Versteeg <thomasversteeg@gmx.com>"
copyright = "2019, Thomas Versteeg <thomasversteeg@gmx.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
A command-line tool to mirror installed software on multiple machines. \
Hooks into your shell to keep track of what you are installing. \
Can also be used to sync configuration files. \
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
	["target/release/emplace", "usr/bin/", "755"],
	["README.md", "usr/share/doc/emplace/README", "644"],
]
